### ISSUE TITLE
[0.6.5 regression] Invalid host: localhost:43110

### ISSUE THREAD

**Issue by yurivict** [HelloZeroNet/ZeroNet#1904]
Browser shows:
```
Forbidden
Invalid host: localhost:43110
```

Command it is started with:
```
python2.7 /usr/local/share/zeronet/zeronet.py --ui_ip 0.0.0.0 --tor always --debug
```

```0.6.4``` works fine on the same system.

FreeBSD 11.2 amd64, installed from the port.

**Comment by bitcoren** [comment]
Try to add "--ui_host localhost:43110"

**Comment by HelloZeroNet** [comment]
There was a change regarding this, please use --ui_host as it was advised by @bitcoren or access it using http://127.0.0.1:43110

**Comment by SirTerrific** [comment]
Hi guys,

Having the same issue in the docker Zeronet. Is there is a env variable to setup it ? 

Thanks for your works.

**Comment by bitcoren** [comment]
You need to install docker-compose and run with the docker-compose.yml.  
Sample file:
```
version: '3'
services:

  proxy:
    container_name: proxy.zites.cf
    image: nofish/zeronet
    restart: always
    environment:
      ENABLE_TOR: "true"
    volumes:
      - ./data:/root/data
      - ./log:/root/log
      - ./zeronet.conf:/root/zeronet.conf
    ports:
      - "26552:26552"
      - "127.0.0.1:43110:43110"
    command: "sh -c ' ( [ -e /root/plugins/disabled-Multiuser ] && rm -rf /root/plugins/Multiuser && mv /root/plugins/disabled-Multiuser /root/plugins/Multiuser ) && (/usr/bin/tor &) && python zeronet.py --ui_host proxy.zites.cf 127.0.0.1:43110 --ui_ip 0.0.0.0 --fileserver_port 26552'"
```
