### ISSUE TITLE
python not found during docker-compose up

### ISSUE THREAD

**Issue by rubo77** [HelloZeroNet/ZeroNet#2500]
I tried to start a zeronode with this docker-compose.yml file, I found [here](https://github.com/HelloZeroNet/ZeroNet/issues/1904#issuecomment-464748094):
```
version: '3'
services:

  proxy:
    container_name: proxy.zites.cf
    image: nofish/zeronet
    restart: always
    environment:
      ENABLE_TOR: "true"
    volumes:
      - ./data:/root/data
      - ./log:/root/log
      - ./zeronet.conf:/root/zeronet.conf
    ports:
      - "26552:26552"
      - "127.0.0.1:43110:43110"
    command: "sh -c ' ( [ -e /root/plugins/disabled-Multiuser ] && rm -rf /root/plugins/Multiuser && mv /root/plugins/disabled-Multiuser /root/plugins/Multiuser ) && (/usr/bin/tor &) && python zeronet.py --ui_host proxy.zites.cf 127.0.0.1:43110 --ui_ip 0.0.0.0 --fileserver_port 26552'"

```
but when I run 

    docker-compose up

It exits with an error:

```

Creating network "zeronet_default" with the default driver
Pulling proxy (nofish/zeronet:)...
latest: Pulling from nofish/zeronet
aad63a933944: Pull complete
01a00972849f: Pull complete
9bddbe39f010: Pull complete
ea7ed6b444e6: Pull complete
Digest: sha256:19aac3fbb8dd7eedf05423e7c6f69a2090a5ee85f21ff6cc50d2e425b469a777
Status: Downloaded newer image for nofish/zeronet:latest
Creating proxy.zites.cf ... done
Attaching to proxy.zites.cf
proxy.zites.cf | sh: python: not found
proxy.zites.cf exited with code 1
